[package]
name = "dplane-rpc"
version = "1.1.2"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bytes = { version = "1.11.1", features = ["serde"] }
log = { version = "0.4.30" }
mac_address = { version = "1.1.8" }
mio = { version = "1.2.1", features = ["net", "os-ext"] }
num-derive = "0.4"
num-traits = "0.2"
tracing = { version = "0.1.44", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3.23" }
tracing-test = { version = "0.2.6" }

[dev-dependencies]
rand = "0.9.4"

[build-dependencies]
cbindgen = { version = "0.27.0" }
