#!/bin/bash

# we indent all .c and .h files EXCEPT for "proto.h"
# (which is autogenerated by build.rs). Tests are not
# re-formatted.
shopt -s extglob
for file in src/!(proto.h|*.txt) ; do
  clang-format-14 --Werror -i -style=file $file
done
shopt -u extglob

