#!/bin/bash

function clib_indent() {
  local file=$1
  indent --indent-level4 \
  --braces-on-if-line \
  --case-indentation4 \
  --tab-size4 \
  --pointer-align-right \
  --case-brace-indentation0 \
  --dont-break-function-decl-args \
  --no-tabs \
  --no-space-after-function-call-names \
  --no-space-after-casts \
  --no-space-after-parentheses \
  --dont-break-procedure-type \
  --no-parameter-indentation \
  --struct-brace-indentation0 \
  --braces-on-struct-decl-line \
  --single-line-conditionals \
  --line-length 100 \
  $file

  # remove indent's backup files
  rm "$file"~
}

# we indent all .c and .h files EXCEPT for "proto.h"
# (which is autogenerated by build.rs). Tests are not
# re-formatted.
shopt -s extglob
for file in src/!(proto.h|*.txt) ; do
  clib_indent $file
done
shopt -u extglob

